MENU_CONFIG = {
    "Administrador": [
        {"id": 1, "nombre": "Configuración", "icono": "Settings", "ruta": "/configuracion", "orden": 1},
        {"id": 2, "nombre": "Dashboard", "icono": "LayoutDashboard", "ruta": "/dashboard", "orden": 2},
        {"id": 3, "nombre": "PEI", "icono": "Target", "ruta": "/pei", "orden": 3},
        {"id": 4, "nombre": "POI", "icono": "ListTodo", "ruta": "/poi", "orden": 4},
        {"id": 5, "nombre": "Programación Multianual", "icono": "Calendar", "ruta": "/programacion", "orden": 5},
        {"id": 6, "nombre": "Presupuesto", "icono": "DollarSign", "ruta": "/presupuesto", "orden": 6},
        {"id": 7, "nombre": "Disponibilidad", "icono": "Wallet", "ruta": "/disponibilidad", "orden": 7},
        {"id": 8, "nombre": "Certificaciones", "icono": "CheckCircle", "ruta": "/certificaciones", "orden": 8},
        {"id": 9, "nombre": "Modificaciones", "icono": "RefreshCw", "ruta": "/modificaciones", "orden": 9},
        {"id": 10, "nombre": "Ejecución", "icono": "TrendingUp", "ruta": "/ejecucion", "orden": 10},
        {"id": 11, "nombre": "Avances", "icono": "BarChart3", "ruta": "/avances", "orden": 11},
        {"id": 12, "nombre": "Evaluación", "icono": "ClipboardCheck", "ruta": "/evaluacion", "orden": 12},
        {"id": 13, "nombre": "Catálogo", "icono": "BookOpen", "ruta": "/catalogos", "orden": 13},
    ],
    "Analista": [
        {"id": 1, "nombre": "Configuración", "icono": "Settings", "ruta": "/configuracion", "orden": 1},
        {"id": 2, "nombre": "Dashboard", "icono": "LayoutDashboard", "ruta": "/dashboard", "orden": 2},
        {"id": 3, "nombre": "PEI", "icono": "Target", "ruta": "/pei", "orden": 3},
        {"id": 4, "nombre": "POI", "icono": "ListTodo", "ruta": "/poi", "orden": 4},
        {"id": 5, "nombre": "Programación Multianual", "icono": "Calendar", "ruta": "/programacion", "orden": 5},
        {"id": 6, "nombre": "Presupuesto", "icono": "DollarSign", "ruta": "/presupuesto", "orden": 6},
        {"id": 7, "nombre": "Disponibilidad", "icono": "Wallet", "ruta": "/disponibilidad", "orden": 7},
        {"id": 8, "nombre": "Certificaciones", "icono": "CheckCircle", "ruta": "/certificaciones", "orden": 8},
        {"id": 9, "nombre": "Modificaciones", "icono": "RefreshCw", "ruta": "/modificaciones", "orden": 9},
        {"id": 10, "nombre": "Ejecución", "icono": "TrendingUp", "ruta": "/ejecucion", "orden": 10},
        {"id": 11, "nombre": "Avances", "icono": "BarChart3", "ruta": "/avances", "orden": 11},
        {"id": 12, "nombre": "Evaluación", "icono": "ClipboardCheck", "ruta": "/evaluacion", "orden": 12},
        {"id": 13, "nombre": "Catálogo", "icono": "BookOpen", "ruta": "/catalogos", "orden": 13},
    ],
    "Auditor": [
        # Solo lectura de módulos
        {"id": 2, "nombre": "Dashboard", "icono": "LayoutDashboard", "ruta": "/dashboard", "orden": 2},
        {"id": 3, "nombre": "PEI", "icono": "Target", "ruta": "/pei", "orden": 3},
        {"id": 4, "nombre": "POI", "icono": "ListTodo", "ruta": "/poi", "orden": 4},
        {"id": 5, "nombre": "Programación Multianual", "icono": "Calendar", "ruta": "/programacion", "orden": 5},
        {"id": 6, "nombre": "Presupuesto", "icono": "DollarSign", "ruta": "/presupuesto", "orden": 6},
        {"id": 7, "nombre": "Disponibilidad", "icono": "Wallet", "ruta": "/disponibilidad", "orden": 7},
        {"id": 8, "nombre": "Certificaciones", "icono": "CheckCircle", "ruta": "/certificaciones", "orden": 8},
        {"id": 9, "nombre": "Modificaciones", "icono": "RefreshCw", "ruta": "/modificaciones", "orden": 9},
        {"id": 10, "nombre": "Ejecución", "icono": "TrendingUp", "ruta": "/ejecucion", "orden": 10},
        {"id": 11, "nombre": "Avances", "icono": "BarChart3", "ruta": "/avances", "orden": 11},
        {"id": 12, "nombre": "Evaluación", "icono": "ClipboardCheck", "ruta": "/evaluacion", "orden": 12},
        {"id": 13, "nombre": "Catálogo", "icono": "BookOpen", "ruta": "/catalogos", "orden": 13},
    ],
}